2025-04-10 17:52:22,645 - cwan - ERROR - Exception on /login [GET]
Traceback (most recent call last):
  File "C:\Users\sanka.dileep\AppData\Local\pypoetry\Cache\virtualenvs\scmxpert-r6r6lqqo-py3.11\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sanka.dileep\AppData\Local\pypoetry\Cache\virtualenvs\scmxpert-r6r6lqqo-py3.11\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sanka.dileep\AppData\Local\pypoetry\Cache\virtualenvs\scmxpert-r6r6lqqo-py3.11\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sanka.dileep\AppData\Local\pypoetry\Cache\virtualenvs\scmxpert-r6r6lqqo-py3.11\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\cwan_project_demo\sample_project\cwanext\sample_project\sample_project.py", line 93, in login
    return render_template("Login.html", signin_template=signin_template, error_message=None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sanka.dileep\AppData\Local\pypoetry\Cache\virtualenvs\scmxpert-r6r6lqqo-py3.11\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sanka.dileep\AppData\Local\pypoetry\Cache\virtualenvs\scmxpert-r6r6lqqo-py3.11\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sanka.dileep\AppData\Local\pypoetry\Cache\virtualenvs\scmxpert-r6r6lqqo-py3.11\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\sanka.dileep\AppData\Local\pypoetry\Cache\virtualenvs\scmxpert-r6r6lqqo-py3.11\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\cwan_project_demo\sample_project\cwanext\sample_project\templates\Login.html", line 4, in top-level template code
    <meta charset="{{ data.head.meta_charset }}">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sanka.dileep\AppData\Local\pypoetry\Cache\virtualenvs\scmxpert-r6r6lqqo-py3.11\Lib\site-packages\jinja2\environment.py", line 490, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'data' is undefined
2025-04-10 17:58:33,623 - cwan - INFO - Logging setup complete
2025-04-10 17:58:33,624 - cwan - INFO - Loading extensions: ['sample_project']
2025-04-10 17:58:34,500 - cwan - INFO - Loaded extension cwanext.sample_project
2025-04-10 17:58:45,979 - cwan - ERROR - Exception on /login [GET]
Traceback (most recent call last):
  File "C:\Users\sanka.dileep\AppData\Local\pypoetry\Cache\virtualenvs\scmxpert-r6r6lqqo-py3.11\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sanka.dileep\AppData\Local\pypoetry\Cache\virtualenvs\scmxpert-r6r6lqqo-py3.11\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sanka.dileep\AppData\Local\pypoetry\Cache\virtualenvs\scmxpert-r6r6lqqo-py3.11\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sanka.dileep\AppData\Local\pypoetry\Cache\virtualenvs\scmxpert-r6r6lqqo-py3.11\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\cwan_project_demo\sample_project\cwanext\sample_project\sample_project.py", line 93, in login
    return render_template("Login.html", signin_template=signin_template, error_message=None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sanka.dileep\AppData\Local\pypoetry\Cache\virtualenvs\scmxpert-r6r6lqqo-py3.11\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sanka.dileep\AppData\Local\pypoetry\Cache\virtualenvs\scmxpert-r6r6lqqo-py3.11\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sanka.dileep\AppData\Local\pypoetry\Cache\virtualenvs\scmxpert-r6r6lqqo-py3.11\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\sanka.dileep\AppData\Local\pypoetry\Cache\virtualenvs\scmxpert-r6r6lqqo-py3.11\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\cwan_project_demo\sample_project\cwanext\sample_project\templates\Login.html", line 6, in top-level template code
    <title>{{ data.head.title }}</title>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sanka.dileep\AppData\Local\pypoetry\Cache\virtualenvs\scmxpert-r6r6lqqo-py3.11\Lib\site-packages\jinja2\environment.py", line 490, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'data' is undefined
2025-04-10 18:00:30,603 - cwan - INFO - Logging setup complete
2025-04-10 18:00:30,604 - cwan - INFO - Loading extensions: ['sample_project']
2025-04-10 18:00:31,774 - cwan - INFO - Loaded extension cwanext.sample_project
2025-04-10 18:00:45,393 - cwan - ERROR - Exception on /login [GET]
Traceback (most recent call last):
  File "C:\Users\sanka.dileep\AppData\Local\pypoetry\Cache\virtualenvs\scmxpert-r6r6lqqo-py3.11\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sanka.dileep\AppData\Local\pypoetry\Cache\virtualenvs\scmxpert-r6r6lqqo-py3.11\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sanka.dileep\AppData\Local\pypoetry\Cache\virtualenvs\scmxpert-r6r6lqqo-py3.11\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sanka.dileep\AppData\Local\pypoetry\Cache\virtualenvs\scmxpert-r6r6lqqo-py3.11\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\cwan_project_demo\sample_project\cwanext\sample_project\sample_project.py", line 93, in login
    return render_template("Login.html", signin_template=signin_template, error_message=None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sanka.dileep\AppData\Local\pypoetry\Cache\virtualenvs\scmxpert-r6r6lqqo-py3.11\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sanka.dileep\AppData\Local\pypoetry\Cache\virtualenvs\scmxpert-r6r6lqqo-py3.11\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sanka.dileep\AppData\Local\pypoetry\Cache\virtualenvs\scmxpert-r6r6lqqo-py3.11\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\sanka.dileep\AppData\Local\pypoetry\Cache\virtualenvs\scmxpert-r6r6lqqo-py3.11\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\cwan_project_demo\sample_project\cwanext\sample_project\templates\Login.html", line 6, in top-level template code
    <title>{{ sign_template.head.title }}</title>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sanka.dileep\AppData\Local\pypoetry\Cache\virtualenvs\scmxpert-r6r6lqqo-py3.11\Lib\site-packages\jinja2\environment.py", line 490, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'sign_template' is undefined
2025-04-10 18:02:49,500 - cwan - INFO - Logging setup complete
2025-04-10 18:02:49,501 - cwan - INFO - Loading extensions: ['sample_project']
2025-04-10 18:02:50,296 - cwan - INFO - Loaded extension cwanext.sample_project
